/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class AIType {
  public final static AIType BT = new AIType("BT");
  public final static AIType NEAT = new AIType("NEAT");
  public final static AIType BT_NEAT = new AIType("BT_NEAT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static AIType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + AIType.class + " with value " + swigValue);
  }

  private AIType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private AIType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private AIType(String swigName, AIType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static AIType[] swigValues = { BT, NEAT, BT_NEAT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

