/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class exampleJNI {
  public final static native long new_IntVec__SWIG_0();
  public final static native long new_IntVec__SWIG_1(long jarg1, IntVec jarg1_);
  public final static native long IntVec_capacity(long jarg1, IntVec jarg1_);
  public final static native void IntVec_reserve(long jarg1, IntVec jarg1_, long jarg2);
  public final static native boolean IntVec_isEmpty(long jarg1, IntVec jarg1_);
  public final static native void IntVec_clear(long jarg1, IntVec jarg1_);
  public final static native long new_IntVec__SWIG_2(int jarg1, int jarg2);
  public final static native int IntVec_doSize(long jarg1, IntVec jarg1_);
  public final static native void IntVec_doAdd__SWIG_0(long jarg1, IntVec jarg1_, int jarg2);
  public final static native void IntVec_doAdd__SWIG_1(long jarg1, IntVec jarg1_, int jarg2, int jarg3);
  public final static native int IntVec_doRemove(long jarg1, IntVec jarg1_, int jarg2);
  public final static native int IntVec_doGet(long jarg1, IntVec jarg1_, int jarg2);
  public final static native int IntVec_doSet(long jarg1, IntVec jarg1_, int jarg2, int jarg3);
  public final static native void IntVec_doRemoveRange(long jarg1, IntVec jarg1_, int jarg2, int jarg3);
  public final static native void delete_IntVec(long jarg1);
  public final static native long new_FloatVec__SWIG_0();
  public final static native long new_FloatVec__SWIG_1(long jarg1, FloatVec jarg1_);
  public final static native long FloatVec_capacity(long jarg1, FloatVec jarg1_);
  public final static native void FloatVec_reserve(long jarg1, FloatVec jarg1_, long jarg2);
  public final static native boolean FloatVec_isEmpty(long jarg1, FloatVec jarg1_);
  public final static native void FloatVec_clear(long jarg1, FloatVec jarg1_);
  public final static native long new_FloatVec__SWIG_2(int jarg1, float jarg2);
  public final static native int FloatVec_doSize(long jarg1, FloatVec jarg1_);
  public final static native void FloatVec_doAdd__SWIG_0(long jarg1, FloatVec jarg1_, float jarg2);
  public final static native void FloatVec_doAdd__SWIG_1(long jarg1, FloatVec jarg1_, int jarg2, float jarg3);
  public final static native float FloatVec_doRemove(long jarg1, FloatVec jarg1_, int jarg2);
  public final static native float FloatVec_doGet(long jarg1, FloatVec jarg1_, int jarg2);
  public final static native float FloatVec_doSet(long jarg1, FloatVec jarg1_, int jarg2, float jarg3);
  public final static native void FloatVec_doRemoveRange(long jarg1, FloatVec jarg1_, int jarg2, int jarg3);
  public final static native void delete_FloatVec(long jarg1);
  public final static native void JavaPorts_init(long jarg1, JavaPorts jarg1_, int jarg2, int jarg3, int jarg4);
  public final static native int JavaPorts_getGeneration(long jarg1, JavaPorts jarg1_);
  public final static native void JavaPorts_saveGeneration(long jarg1, JavaPorts jarg1_, String jarg2);
  public final static native void JavaPorts_loadGeneration(long jarg1, JavaPorts jarg1_, String jarg2, int jarg3);
  public final static native void JavaPorts_evolve(long jarg1, JavaPorts jarg1_);
  public final static native void JavaPorts_setFitness(long jarg1, JavaPorts jarg1_, int jarg2, int jarg3);
  public final static native void JavaPorts_setBehavior(long jarg1, JavaPorts jarg1_, int jarg2, long jarg3, IntVec jarg3_);
  public final static native void JavaPorts_setTargetSpecies(long jarg1, JavaPorts jarg1_, int jarg2);
  public final static native void JavaPorts_setSurpriseEffect(long jarg1, JavaPorts jarg1_, float jarg2);
  public final static native void JavaPorts_mapElites(long jarg1, JavaPorts jarg1_);
  public final static native void JavaPorts_randomizePopulation(long jarg1, JavaPorts jarg1_, int jarg2, int jarg3);
  public final static native void JavaPorts_randomizePopulationFromElites(long jarg1, JavaPorts jarg1_);
  public final static native void JavaPorts_saveElites__SWIG_0(long jarg1, JavaPorts jarg1_, String jarg2);
  public final static native void JavaPorts_saveElites__SWIG_1(long jarg1, JavaPorts jarg1_);
  public final static native void JavaPorts_loadElites__SWIG_0(long jarg1, JavaPorts jarg1_, String jarg2);
  public final static native void JavaPorts_loadElites__SWIG_1(long jarg1, JavaPorts jarg1_);
  public final static native void JavaPorts_storeElites(long jarg1, JavaPorts jarg1_);
  public final static native void JavaPorts_calcNEATInput(long jarg1, JavaPorts jarg1_, int jarg2, long jarg3, FloatVec jarg3_);
  public final static native long JavaPorts_getNEATOutput(long jarg1, JavaPorts jarg1_, int jarg2);
  public final static native void JavaPorts_calcNEATEliteInput(long jarg1, JavaPorts jarg1_, int jarg2, long jarg3, FloatVec jarg3_);
  public final static native long JavaPorts_getNEATEliteOutput(long jarg1, JavaPorts jarg1_, int jarg2);
  public final static native void JavaPorts_insertEliteIntoGeneration(long jarg1, JavaPorts jarg1_, int jarg2, int jarg3);
  public final static native void JavaPorts_resetRecurrentState(long jarg1, JavaPorts jarg1_, int jarg2);
  public final static native long new_JavaPorts();
  public final static native void delete_JavaPorts(long jarg1);
}
